.set STK_DEPTH, 24

.set USER_UID, (0 * 4)
.set USER_NXT, (1 * 4)
.set USER_TOS, (2 * 4)
.set USER_RAP, (3 * 4)
.set USER_PS0, (4 * 4)
.set USER_PSP, (5 * 4)
.set USER_RS0, (6 * 4)
.set USER_RSP, (7 * 4)
.set USER_EMITAVA, (8 * 4)
.set USER_EMIT,    (9 * 4)
.set USER_KEYAVA,  (10 * 4)
.set USER_KEY,     (11 * 4)
.set USER_DOT,     (12 * 4)
.set USER_WIB,     (13 * 4)
.set USER_WIN,     (14 * 4)
.set USER_STATE,   (15 * 4)

.set TOS_INIT, 0xDEADBEEF

.set USER_SIZE, (24 * 4)
.set CONTEXT_MAX, 8

.set FORTH_TRUE, 0xFFFFFFFF
.set FORTH_FALSE, 0x00000000
.set WORD_NLEN_MAX, 0x3F
